# Site settings
title:
email: contact@iggg.org
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/guntoh-fes" # the subpath of your site, e.g. /blog/
url: "https://iggg.github.io" # the base hostname & protocol for your site

twitter_username: IGGGorg
github_username: IGGG

# Build settings
markdown: kramdown

plugins:
- jekyll-redirect-from
